# Generated by Django 3.2.3 on 2021-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windSpeed', models.FloatField(default=0)),
                ('airTemperature', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('currentSpeed', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('iceCover', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('seaLevel', models.FloatField(default=0)),
                ('swellDirection', models.FloatField(default=0)),
                ('swellHeight', models.FloatField(default=0)),
                ('swellPeriod', models.FloatField(default=0)),
                ('secondarySwellPeriod', models.FloatField(default=0)),
                ('secondarySwellDirection', models.FloatField(default=0)),
                ('secondarySwellHeight', models.FloatField(default=0)),
                ('visibility', models.FloatField(default=0)),
                ('waterTemperature', models.FloatField(default=0)),
                ('waveDirection', models.FloatField(default=0)),
                ('waveHeight', models.FloatField(default=0)),
                ('wavePeriod', models.FloatField(default=0)),
                ('windWaveDirection', models.FloatField(default=0)),
                ('windWaveHeight', models.FloatField(default=0)),
            ],
        ),
    ]
